version: 0.2

phases:
  install:
    commands:
      - echo Install
  build:
    commands:
      - echo Build started on 'date'
      - ghdl -a hello.vhdl
      - ghdl -e hello_world
      - ghdl -r hello_world > output.txt
  post_build:
    commands:
      - echo build completed on 'date'
artifacts:
  files:
    - output.txt